### ISSUE TITLE
haskell-language-server fails to start when IDEA is not started from the project directory

### ISSUE THREAD

**Issue by develop7** [rockofox/intellij-haskell-lsp#14]
Repro:

1. start IDEA with from a desktop/menu/JB Toolbox
2. Open project in Haskell

Expected: HLS does start 

Instead: HLS doesn't start citing following error:

```
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: Unable to start language server: ProcessStreamConnectionProvider [commands=[/home/adziahel/.ghcup/bin/haskell-language-server-wrapper, --lsp], workingDir=/home/adziahel/projects/postgrest/postgrest]
	at com.redhat.devtools.lsp4ij.server.ProcessStreamConnectionProvider.ensureIsAlive(ProcessStreamConnectionProvider.java:88)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$3(LanguageServerWrapper.java:297)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
com.redhat.devtools.lsp4ij.server.CannotStartProcessException: Unable to start language server: ProcessStreamConnectionProvider [commands=[/home/adziahel/.ghcup/bin/haskell-language-server-wrapper, --lsp], workingDir=/home/adziahel/projects/postgrest/postgrest]
	at com.redhat.devtools.lsp4ij.server.ProcessStreamConnectionProvider.ensureIsAlive(ProcessStreamConnectionProvider.java:88)
	at com.redhat.devtools.lsp4ij.LanguageServerWrapper.lambda$start$3(LanguageServerWrapper.java:297)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
```

Workaround: start IDEA with the shell script from the project directory

**Comment by develop7** [comment]
Cannot reproduce the issue anymore after the updating the LSP4IJ plugin to 0.9.0
